// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/blog/[slug].tsx";
import * as $3 from "./routes/blog/index.tsx";
import * as $4 from "./routes/contact.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/projects/[slug].tsx";
import * as $7 from "./routes/projects/index.tsx";
import * as $8 from "./routes/resources.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/blog/[slug].tsx": $2,
    "./routes/blog/index.tsx": $3,
    "./routes/contact.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/projects/[slug].tsx": $6,
    "./routes/projects/index.tsx": $7,
    "./routes/resources.tsx": $8,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
